sudo: false

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
      - docker-ce

env:
  global:
    - KITCHEN_YAML=.kitchen.travis.yml
  matrix:
    - platform=centos-7

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - master

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/bin/chef gem install kitchen-docker

script:
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/bin/kitchen test
